// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZV_Bc8Sp2lZyxm4b8sGjByJcrOsc0GLY',
    appId: '1:704273651670:web:53d0c4441d08f91b137677',
    messagingSenderId: '704273651670',
    projectId: 'taskk5',
    authDomain: 'taskk5.firebaseapp.com',
    storageBucket: 'taskk5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5wLfVRGwSd8izKc9uAE2wKNpO_DnAB6w',
    appId: '1:704273651670:android:c73aa8fc6ba5c9ec137677',
    messagingSenderId: '704273651670',
    projectId: 'taskk5',
    storageBucket: 'taskk5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7RePTeONplmq24tc6SRIRqKPSCulhF8',
    appId: '1:704273651670:ios:9db868e821e9a154137677',
    messagingSenderId: '704273651670',
    projectId: 'taskk5',
    storageBucket: 'taskk5.appspot.com',
    iosClientId: '704273651670-aeti9i3ocuq2hs1bbo7a9njfpqd59vvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskk5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm7RePTeONplmq24tc6SRIRqKPSCulhF8',
    appId: '1:704273651670:ios:d07eb1db045889a6137677',
    messagingSenderId: '704273651670',
    projectId: 'taskk5',
    storageBucket: 'taskk5.appspot.com',
    iosClientId: '704273651670-eug0cvr2cjejkp9j1vuv8vsli7dbdip1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskk5.RunnerTests',
  );
}
